# Generated by Django 4.2.7 on 2023-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
