# Generated by Django 4.2.7 on 2023-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0003_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('Ambulance_No', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('Ambulance_type', models.CharField(choices=[('Basic', 'Basic Life Support Ambulance'), ('Advance', 'Advance Life Support Ambulance'), ('Patient', 'Patient Transfer Ambulance'), ('Mortuary', 'Mortuary Ambulance')], max_length=50)),
                ('Status', models.CharField(choices=[('Active', 'Available'), ('Inactive', 'Unavailable')], max_length=50)),
            ],
        ),
    ]
