# Generated by Django 4.2.7 on 2023-11-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0005_alter_ambulance_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='Status',
            new_name='ambulanceStatus',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='Ambulance_type',
            new_name='ambulanceType',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='password',
            new_name='driverPassword',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='email',
            new_name='emailAddress',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='Phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='username',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='Ambulance_No',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='ambulanceNumber',
            field=models.CharField(default='exit', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
