# Generated by Django 4.2.7 on 2023-11-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0006_rename_status_ambulance_ambulancestatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='firstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='lastName',
            new_name='LastName',
        ),
    ]
