# Generated by Django 4.2.7 on 2023-11-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0008_rename_ambulancenumber_ambulance_ambulance_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulance_number',
            new_name='ambulanceNumber',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulance_status',
            new_name='ambulanceStatus',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulance_type',
            new_name='ambulanceType',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='user_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='driver_password',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='username',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
