# Generated by Django 4.2.7 on 2023-11-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0009_rename_ambulance_number_ambulance_ambulancenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulanceNumber',
            new_name='Ambulance_No',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulanceType',
            new_name='Ambulance_type',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='phoneNumber',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulanceStatus',
            new_name='Status',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
