# Generated by Django 4.2.7 on 2023-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0011_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
