# Generated by Django 4.2.7 on 2023-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0014_alter_ambulance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='Ambulance_type',
            field=models.CharField(choices=[('Basic Life Support Ambulance', 'Basic'), ('Advance Life Support Ambulance', 'Advance'), ('Patient Transfer Ambulance', 'Patient'), ('Mortuary Ambulance', 'Mortuary')], max_length=50),
        ),
    ]
