# Generated by Django 4.2.7 on 2023-11-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0015_alter_ambulance_ambulance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='Ambulance_type',
            field=models.CharField(choices=[('Basic', 'Basic Life Support Ambulance'), ('Advance', 'Advance Life Support Ambulance'), ('Patient', 'Patient Transfer Ambulance'), ('Mortuary', 'Mortuary Ambulance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='Status',
            field=models.CharField(choices=[('Active', 'Available'), ('Inactive', 'Unavailable')], max_length=50),
        ),
    ]
