# Generated by Django 4.2.7 on 2023-11-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceApp', '0016_alter_ambulance_ambulance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='Ambulance_type',
            field=models.CharField(choices=[('Basic Life Support Ambulance', 'Basic Life Support Ambulance'), ('Advance Life Support Ambulance', 'Advance Life Support Ambulance'), ('Patient Transfer Ambulance', 'Patient Transfer Ambulance'), ('Mortuary Ambulance', 'Mortuary Ambulance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50),
        ),
    ]
